const express = require('express');
const cors = require('cors');
const path = require('path');
const fs = require('fs');
const https = require('https');

const app = express();
const PORT = 3000;

app.use(cors());
app.use(express.static(path.join(__dirname, 'src')));
app.use('/assets', express.static(path.join(__dirname, 'assets')));

// Serve manifest at root for easy sideloading
app.get('/manifest.xml', (req, res) => {
  res.sendFile(path.join(__dirname, 'manifest.xml'));
});

// Knowledge base persistence (local JSON file — never leaves device)
const KB_FILE = path.join(__dirname, 'knowledge-base.json');

app.use(express.json());

app.get('/api/kb', (req, res) => {
  try {
    const data = fs.existsSync(KB_FILE) ? JSON.parse(fs.readFileSync(KB_FILE)) : [];
    res.json(data);
  } catch { res.json([]); }
});

app.post('/api/kb', (req, res) => {
  try {
    fs.writeFileSync(KB_FILE, JSON.stringify(req.body, null, 2));
    res.json({ ok: true });
  } catch (e) { res.status(500).json({ error: e.message }); }
});

// Check if SSL certs exist (generated by setup script)
const certPath = path.join(__dirname, 'certs');
const keyFile  = path.join(certPath, 'server.key');
const certFile = path.join(certPath, 'server.crt');

if (fs.existsSync(keyFile) && fs.existsSync(certFile)) {
  const options = {
    key:  fs.readFileSync(keyFile),
    cert: fs.readFileSync(certFile),
  };
  https.createServer(options, app).listen(PORT, () => {
    console.log(`\n✅ Excel Expert Add-in running at https://localhost:${PORT}`);
    console.log(`\n📋 Next step: sideload the manifest in Excel`);
    console.log(`   File > Options > Trust Center > Trust Center Settings`);
    console.log(`   > Trusted Add-in Catalogs > add: https://localhost:${PORT}\n`);
  });
} else {
  // Fallback: HTTP (works for development, not for production sideloading)
  app.listen(PORT, () => {
    console.log(`\n⚠️  Running on HTTP (http://localhost:${PORT})`);
    console.log(`   Run setup.bat first to generate SSL certificates for full Excel integration.\n`);
  });
}
